### ISSUE TITLE
Fix shop image hexagons in PaymentInfoLine

### ISSUE THREAD

**Issue by Bettelstab** [nimiq/vue-components#24]
Outline and clip are not aligned.
Edit: Added screenshot.
![image](https://user-images.githubusercontent.com/3285528/57071137-cf1d0780-6cd9-11e9-92f5-540d113e4dde.png)

**Comment by sisou** [comment]
Can you provide a screenshot? They look pretty aligned to me.

**Comment by Bettelstab** [comment]
There was this demo with a big burger company's logo... Any idea where that came from?

**Comment by sisou** [comment]
This one?

https://github.com/nimiq/vue-components/blob/master/src/stories/index.stories.js#L492

**Comment by Bettelstab** [comment]
Yes, thanks.

**Comment by sisou** [comment]
Shop Logos are no longer clipped.
