### ISSUE TITLE
Copyable should correctly copy numbers passed as 'text' prop

### ISSUE THREAD

**Issue by sisou** [nimiq/vue-components#88]
Currently, numbers are copied wrongly. The component should call `.toString()` on all non-string values passed to its `text` prop.

Reported by Ken Blazer in Discord#coders-dojo.

**Comment by danimoh** [comment]
Not sure what is meant by this.
The `text` prop is constrained to `String`s which is checked by Vue.
I could not reproduce any issues in that regard.
If the parent component wants to pass any other value, it should be his responsibility to convert it into an appropriate string representation.
